package com.spiralboss;

public enum NewsRegionLanguage {
	AregentinaSpanish("es-ar"),
	AustriaGerman("de-at"),
	AustraliaEnglish("en-au"),
	BrazilPortugese("pt-br"),
	CanadaEnglish("en-ca"),
	CanadaFrench("fr-ca"),
	ChileSpanish("es-cl"),
	ColombiaSpanish("es-co"),
	CzechRepublicCzech("cs-cz"),
	DenmarkDanish("da-dk"),
	FinlandFinnish("fl-fl"),
	FranceFrench("fr-fr"),
	GermanyGerman("de-de"),
	HongKongChineseSimplified("zh-hant-hk"),
	HungaryHungarian("hu-hu"),
	IndonesiaEnglish("id-en"),
	IndonesiaIndonesian("id-id"),
	IndiaEnglish("en-in"),
	IsraelHebrew("he-il"),
	ItalyItalian("it-it"),
	JapanJapanese("ja-jp"),
	KoreaKorean("ko-kr"),
	MalaysiaEnglish("en-my"),
	MalaysiaMalaysian("ms-my"),
	MexicoSpanish("es-mx"),
	NetherlandsDutch("nl-nl"),
	NewZealandEnglish("en-nz"),
	NorwayNorwegian("no-no"),
	PeruSpanish("es-pe"),
	PhilippinesFilipino("tl-ph"),
	PhilippinesEnglish("en-ph"),
	RomaniaRomanian("ro-ro"),
	RussiaRussian("ru-ru"),
	SingaporeEnglish("en-sg"),
	SpainCatalan("ca-es"),
	SpainSpanish("es-es"),
	SwedenSwedish("sv-se"),
	SwitzerlandFrench("fr-ch"),
	SwitzerlandGerman("de-ch"),
	SwitzerlandItalian("it-ch"),
	ThailandThai("th-th"),
	TaiwanChineseTraditional("zh-hant-tw"),
	TurkeyTurkish("tr-tr"),
	UnitedKingdomEnglish("en-gb"),
	UnitedStatesEnglish("en-us"),
	UnitedStatesSpanish("es-us"),
	VietnamVietnamese("vi-vn");
	
	private final String code;
	NewsRegionLanguage(String code) { this.code = code; }
    public String getCode() { return this.code; }
}
